### ISSUE TITLE
1.21 Recipe bug...

### ISSUE THREAD

**Issue by makumaku1974** [AzureDoom/Azure-Paxels#15]
No Recipe

**Comment by AzureDoom** [comment]
https://github.com/AzureDoom/Azure-Paxels/tree/1.21.x/common/src/main/resources/data/azurepaxels/recipes ah damn it mojang, they changed `recipes` to `recipe`. Fix will be out in a few hours!

**Comment by makumaku1974** [comment]
Also please nerf all of them for being too fast to break blocks. Tested it back in 1.20.6

**Comment by AzureDoom** [comment]
That's intended.
