### ISSUE TITLE
Settings for mine speed

### ISSUE THREAD

**Issue by WolfKnight98** [AzureDoom/Azure-Paxels#16]
I understand the intended design is to have the paxels mine fast, but it feels silly unless you're using an enchanted tool. Please consider adding an option to adjust the mining speeds, so that the paxels reflect their respective tier.

**Comment by GanerCodes** [comment]
I agree, ideally a mod like this is literally just a bundle of tools that automatically switches based on what you're breaking (and can hoe/make paths)

**Comment by AzureDoom** [comment]
I can add a configuration but please note, I will end up using my common library for this, AzureLib. If that's fine, I'll do it next update.

**Comment by xardius** [comment]
I would also love to have just the "standard" speed. The additional library is no problem imho.

Adding a Sword/Hoe into the tools would be nice to :P

**Comment by Leonniclass** [comment]
Ah thank god, I thought it was a bug or incompatibility. My modpack uses a wooden paxel as a starter kit and that item is hella strong for a wooden tier now

**Comment by AzureDoom** [comment]
As this is a breaking change, this will be a 1.21.1+ only feature.
