### ISSUE TITLE
Durability is wrong?

### ISSUE THREAD

**Issue by Knito58** [AzureDoom/Azure-Paxels#17]
Fabric 1.21, azure paxels 1.0.3 (newest atm)

Dia Shovel = 1561
Dia Axe = 1561
Dia Pick = 1561

Dia Paxel = Dia Shovel + Dia Axe + Dia Pick (+ 2 sticks) => 1561 ????

When crafting a dia paxel you lose 2 dia tools worth of durability. I'd rather use the singleton tools themselves because this is not eco at all. I suggest a durability for the dp as such: 3 x 1561 + little extra => 5000

**Comment by AzureDoom** [comment]
The tools use the durability granted by the material; I don't change anything material-wise.
